import { Link } from "react-router-dom";
import Topbar from "../../components/Topbar";
import { Sparkles, MapPin, Clock, Wallet } from "lucide-react";
import { opportunities, recommended, currentApplicant } from "../../data/mockData";

export default function Recommended() {
  const withDetail = recommended.map((r) => ({ ...r, opp: opportunities.find((o) => o.id === r.id) }));

  return (
    <>
      <Topbar
        eyebrow="Applicant" title="Recommended for You" subtitle="Matched to your NQF level, qualifications and tagged skills."
        notifCount={3} msgCount={2}
        user={{ name: currentApplicant.name, role: "Applicant", initials: currentApplicant.initials, color: "var(--veld)" }}
      />
      <div className="page">
        <div className="card" style={{ marginBottom: 20, background: "var(--sun-tint)", border: "none", display: "flex", gap: 14, alignItems: "center" }}>
          <Sparkles size={22} color="var(--sun-deep)" />
          <p className="text-sm" style={{ color: "var(--ink-soft)" }}>
            These matches are generated by comparing your tagged skills and NQF level against each
            open opportunity's stated requirements — a baseline scoring signal that a smarter
            matching model can build on later.
          </p>
        </div>

        <div className="grid grid-3">
          {withDetail.map(({ opp, match, nqf }) => opp && (
            <div key={opp.id} className="opp-card">
              <div className="opp-card-top">
                <span className="badge badge-sun">{opp.type}</span>
                <span className="badge badge-veld">{match}% match</span>
              </div>
              <div>
                <h4>{opp.title}</h4>
                <p className="text-sm text-stone" style={{ marginTop: 4 }}>{opp.provider} · {opp.sector}</p>
              </div>
              <div className="opp-meta">
                <span><MapPin size={13} /> {opp.location}</span>
                <span><Clock size={13} /> {opp.duration} months</span>
                <span><Wallet size={13} /> R{opp.stipend.toLocaleString()}/mo</span>
              </div>
              <div className="chip-row">
                {opp.requiredSkills.map((s) => <span className="chip" key={s} style={{ fontSize: 11.5, padding: "4px 9px" }}>{s}</span>)}
              </div>
              <Link to={`/applicant/opportunities/${opp.id}`} className="btn btn-primary btn-sm">View &amp; Apply</Link>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
